In [ ]:
from sklearn.datasets import load_wine
import numpy as np
wine_dataset = load_wine()

A =wine_dataset.data

print(A.shape)

y = wine_dataset.target

print(y.shape)

(178, 13)
(178,)


#Q.1

In [ ]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


**Clearly the class labels are from the set {0,1,2,....c}.**

#Q.2

In [ ]:

for x in range(y.shape[0]):
  if y[x]==1:
    y[x]=1
  else:
    y[x] = -1

print(y)

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


#Q.3

In [ ]:
print(A)
for i in range(A.shape[1]):
  A[:,i] = (A[:,i] - np.min(A[:,i]))/(np.max(A[:,i]) - np.min(A[:,i]))
print(A)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[[0.84210526 0.1916996  0.57219251 ... 0.45528455 0.97069597 0.56134094]
 [0.57105263 0.2055336  0.4171123  ... 0.46341463 0.78021978 0.55064194]
 [0.56052632 0.3201581  0.70053476 ... 0.44715447 0.6959707  0.64693295]
 ...
 [0.58947368 0.69960474 0.48128342 ... 0.08943089 0.10622711 0.39728959]
 [0.56315789 0.36561265 0.54010695 ... 0.09756098 0.12820513 0.40085592]
 [0.81578947 0.66403162 0.73796791 ... 0.10569106 0.12087912 0.20114123]]


**Used Min-max normalisation technique to do this task**

#Q.4

In [ ]:
n = A.shape[0]

indexarr = np.arange(n) #index array
np.random.shuffle(indexarr)

train_data = []
train_label = []
test_data = []
test_label = []
counter = 1
for i in indexarr:
  if counter <= int(0.8*n):
    train_data.append(list(A[i,:]))
    train_label.append(y[i])
  else:
    test_data.append(list(A[i]))
    test_label.append(y[i])
  counter = counter + 1
train_data = np.array(train_data)
train_label = np.array(train_label).reshape(np.array(train_label).shape[0],1)
test_data = np.array(test_data)
test_label = np.array(test_label).reshape(np.array(test_label).shape[0],1)

In [ ]:
print(len(train_label)/len(y))
print(len(test_label)/len(y))
print(len(train_data)/len(A))
print(len(test_data)/len(A))

0.797752808988764
0.20224719101123595
0.797752808988764
0.20224719101123595


#Q.5

In [ ]:
def predict(w,x):
  if w.T@x > 0:
    return 1
  else:
    return -1

#Q.6

In [ ]:
def compute_accuracy(data,labels,model_w):
  n=data.shape[0]
  c=0
  for i in range(n):
    if predict(model_w,data[i])==labels[i]:
      c+=1
  return c*100/n